# ===================================================================
# Main Application Configuration
# ===================================================================
spring.application.name=ai-logistics-incident-reporter

# Profile hoạt động mặc định khi khởi chạy không truyền tham số
spring.profiles.active=local

# Cấu hình Server Port
server.port=8080
